version: '3'

services:
  web:
      build:
          context: .
      command: 
        - bash
      container_name: "osmosisapi"
      ports:
          - 80:8000
      volumes: 
          - .:/app

      entrypoint: bash -c "gunicorn osmosis_music_api.wsgi:application -b :8000 --timeout 300 -w 1 -k gevent"
