# Generated by Django 2.1.5 on 2020-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSettings',
            fields=[
                ('ads_id', models.AutoField(primary_key=True, serialize=False)),
                ('ads_title', models.TextField()),
                ('ads_id_value', models.TextField()),
                ('ads_status', models.CharField(max_length=7)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ads_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiListParameters',
            fields=[
                ('api_list_parameters_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_list_id', models.IntegerField()),
                ('api_list_parameters_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'api_list_parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('artist_image', models.CharField(blank=True, max_length=100, null=True)),
                ('artist_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_email', models.TextField(blank=True, null=True)),
                ('user_password', models.TextField(blank=True, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('user_profile_pic', models.CharField(blank=True, max_length=100, null=True)),
                ('user_package_id', models.IntegerField(blank=True, null=True)),
                ('user_package_paid_date', models.DateTimeField(blank=True, null=True)),
                ('user_package_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user_token', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.TextField()),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_password', models.TextField()),
                ('status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_id', models.CharField(max_length=100)),
                ('album_name', models.CharField(blank=True, max_length=100, null=True)),
                ('album_image', models.CharField(blank=True, max_length=100, null=True)),
                ('album_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'album',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApiList',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.TextField()),
                ('api_link', models.TextField()),
                ('api_type', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('banner_slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_slider_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('banner_slider_name_alignment', models.CharField(max_length=6)),
                ('banner_slider_image', models.CharField(max_length=1000)),
                ('banner_slider_show_button', models.IntegerField()),
                ('banner_slider_button_alignment', models.CharField(max_length=6)),
                ('banner_slider_button_text', models.CharField(blank=True, max_length=20, null=True)),
                ('banner_slider_order', models.IntegerField()),
                ('banner_slider_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banner_slider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('parent_category_id', models.IntegerField()),
                ('category_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HomeComponents',
            fields=[
                ('home_components_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_components_name', models.CharField(max_length=100)),
                ('home_components_description', models.TextField()),
                ('home_components_item_display_count', models.IntegerField(blank=True, null=True)),
                ('home_components_order', models.IntegerField()),
                ('home_components_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'home_components',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('like_type', models.CharField(max_length=7)),
                ('like_type_id', models.IntegerField()),
                ('like_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'liked',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=500)),
                ('movie_description', models.TextField()),
                ('movie_image', models.CharField(max_length=100)),
                ('movie_year', models.CharField(max_length=10)),
                ('movie_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False)),
                ('music_title', models.TextField()),
                ('music_file', models.CharField(max_length=100)),
                ('music_image', models.CharField(max_length=100)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('album_id', models.IntegerField()),
                ('artist_id', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField(blank=True, null=True)),
                ('music_size', models.CharField(blank=True, max_length=50, null=True)),
                ('music_duration', models.CharField(max_length=10)),
                ('music_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'music',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('settings_name', models.TextField()),
                ('settings_value', models.TextField()),
                ('settings_status', models.CharField(max_length=7)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PackageSettings',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=1000)),
                ('package_duration', models.CharField(max_length=100)),
                ('package_price', models.CharField(max_length=100)),
                ('package_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=7)),
                ('package_note', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'package_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=100)),
                ('payment_method_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_method_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method_status', models.CharField(max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecentlyView',
            fields=[
                ('recently_view_id', models.AutoField(primary_key=True, serialize=False)),
                ('recently_view_type', models.CharField(max_length=6)),
                ('recently_view_type_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'recently_view',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SettingsFlag',
            fields=[
                ('settings_flag_id', models.AutoField(primary_key=True, serialize=False)),
                ('settings_flag_name', models.CharField(max_length=100)),
                ('settings_flag_value', models.CharField(max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settings_flag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('user_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('package_id', models.IntegerField()),
                ('card_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('expiration_month', models.IntegerField()),
                ('expiration_year', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('user_playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_playlist_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_playlist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPlaylistMusic',
            fields=[
                ('user_playlist_music_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_playlist_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('music_id', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_playlist_music',
                'managed': True,
            },
        ),
    ]
