# Generated by Django 2.1.5 on 2019-07-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(blank=True, max_length=1000)),
                ('image', models.CharField(blank=True, max_length=2000)),
                ('language', models.CharField(choices=[('English', 'English'), ('Nepali', 'Nepali'), ('Hindi', 'Hindi'), ('Dzongkha', 'Dzongkha')], default='English', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('cover_art', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('genre', models.CharField(choices=[('Unknown', 'Unknown'), ('Movie', 'Movie'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Alternative/Indie', 'Alternative/Indie'), ('Remix', 'Remix'), ('Instrumental', 'Instrumental'), ('Folk', 'Folk'), ('Electronic', 'Electronic')], default='Unknown', max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Nepali', 'Nepali'), ('Hindi', 'Hindi'), ('Dzongkha', 'Dzongkha')], default='English', max_length=10)),
                ('artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='music_core.Artist')),
                ('playlist', models.ManyToManyField(to='music_core.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('genre', models.CharField(choices=[('Unknown', 'Unknown'), ('Movie', 'Movie'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Alternative/Indie', 'Alternative/Indie'), ('Remix', 'Remix'), ('Instrumental', 'Instrumental'), ('Folk', 'Folk'), ('Electronic', 'Electronic')], default='Unknown', max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Nepali', 'Nepali'), ('Hindi', 'Hindi'), ('Dzongkha', 'Dzongkha')], default='English', max_length=10)),
                ('image', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='music_core.Artist')),
            ],
        ),
    ]
