# Generated by Django 2.1.5 on 2020-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_status',
            field=models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_status',
            field=models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_status',
            field=models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='homecomponent',
            name='home_components_status',
            field=models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='settings_status',
            field=models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='packagesettings',
            name='package_status',
            field=models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method_status',
            field=models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10),
        ),
    ]
