# Generated by Django 2.1.5 on 2020-09-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
