# Generated by Django 2.1.5 on 2019-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
