# Generated by Django 2.1.5 on 2020-10-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
