# Generated by Django 2.1.5 on 2020-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0002_auto_20200929_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_slider_id', models.IntegerField()),
                ('banner_slider_name', models.CharField(max_length=1000)),
                ('banner_slider_name_alignment', models.CharField(choices=[(0, 'Left'), (1, 'Center'), (2, 'Right')], max_length=10)),
                ('banner_slider_image', models.CharField(max_length=1000)),
                ('banner_slider_show_button', models.IntegerField()),
                ('banner_slider_button_alignment', models.CharField(choices=[(0, 'Left'), (1, 'Center'), (2, 'Right')], max_length=10)),
                ('banner_slider_button_text', models.CharField(max_length=20)),
                ('banner_slider_order', models.IntegerField()),
                ('banner_slider_status', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banner_slider',
            },
        ),
    ]
