# Generated by Django 2.1.5 on 2020-09-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_package_id',
            field=models.IntegerField(default=0),
        ),
    ]
