# Generated by Django 2.1.5 on 2020-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0003_bannerslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings_flag_id', models.IntegerField()),
                ('settings_flag_name', models.CharField(max_length=100)),
                ('settings_flag_valye', models.CharField(choices=[(0, 'ENABLE'), (1, 'DISABLE')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settings_flag',
            },
        ),
    ]
