# Generated by Django 2.1.5 on 2020-09-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0004_auto_20200930_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerslider',
            name='banner_slider_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='homecomponent',
            name='home_components_id',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='packagesettings',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment_method_id',
        ),
        migrations.RemoveField(
            model_name='settingsflag',
            name='settings_flag_id',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='user_payment_id',
        ),
    ]
