# Generated by Django 2.1.5 on 2020-09-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0006_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
