# Generated by Django 2.1.5 on 2020-09-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_core', '0007_auto_20200930_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='last_modified',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='last_modified',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='last_modified',
            new_name='last_updated',
        ),
    ]
